# Generated by Django 4.2.5 on 2023-12-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('authorname', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
                ('relativetimedescription', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
